#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as H from '../.agents/skills/travel-itinerary/scripts/itinerary-helpers.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const template = JSON.parse(fs.readFileSync(path.join(root, 'src/_data/madeira-crete/main.json'), 'utf8'));
const sourceSpots = template.itinerary.days.flatMap((day) => day.spots || []);
const outDir = path.join(root, 'src/_data/crete');
const asset = (file) => `../../assets/img/crete/${file}`;
const photoPlan = JSON.parse(fs.readFileSync(path.join(root, 'assets/img/crete/_photo-plan.json'), 'utf8'));

const photoCarousel = (carouselId) => (photoPlan.carousels[carouselId] || []).map((image) => ({
  href: asset(image.file), src: asset(image.file), alt: image.alt,
  captionTitle: image.captionTitle, credit: image.credit,
}));

const pick = (name, carouselId, selectedImages) => {
  const original = sourceSpots.find((spot) => spot.name === name);
  if (!original) throw new Error(`Missing Crete source spot: ${name}`);
  return { ...structuredClone(original), carouselId, images: selectedImages };
};

const chania = pick('Chania old town + Nea Chora / Agii Apostoli', 'crete-chania', photoCarousel('crete-chania'));
const balos = pick('Balos Lagoon by Kissamos boat', 'crete-balos', photoCarousel('crete-balos'));
const elafonissi = pick('Elafonissi Lagoon or Falasarna sunset', 'crete-elafonissi', photoCarousel('crete-elafonissi'));
const imbros = pick('Imbros Gorge + south-coast swim', 'crete-imbros', photoCarousel('crete-imbros'));
const rethymno = pick('Rethymno old town + Fortezza + beach', 'crete-rethymno', photoCarousel('crete-rethymno'));
const preveli = pick('Preveli Palm Beach + Kourtaliotiko Gorge', 'crete-preveli', photoCarousel('crete-preveli'));

const mk = (data) => H.mkSpot({
  tags: ['crete', 'greece'], climateLabel: 'June conditions', ...data,
});

const knossos = mk({
  name: 'Knossos Palace en route to eastern Crete', carouselId: 'crete-knossos',
  images: photoCarousel('crete-knossos'), lat: 35.2989, lng: 25.1631,
  cost: 'The official current ticket is €20 full / €10 reduced, with daily summer hours 08:00–20:00 and timed entry. Budget about €40–€60 for the family depending on youth eligibility; recheck the official Hellenic Heritage ticket page for 2027.',
  climate: '<b>Go at 08:00.</b> The open archaeological site becomes hot and busy by late morning. Carry hats and water, then use the air-conditioned drive east as the day’s recovery block.',
  save: 'Use the official ticket site and a family audio guide rather than buying a marked-up transfer from Rethymno.',
  splurge: 'A licensed private guide who can make the Labyrinth, Minotaur and archaeology land for both kids.',
  restos: ['<b>Pasiphae Restaurant near Knossos</b> — pizza, pasta and grilled meat.', '<b>Heraklion bakery stop</b> — pies, sandwiches and fruit for the drive.', '<b>Agios Nikolaos apartment dinner</b> — the no-drama arrival fallback.'],
  alts: ['<b>Heraklion Archaeological Museum</b> if heat closes the exposed site.', '<b>Skip the museum add-on</b> and reach Agios Nikolaos for a late swim.'],
  blogs: [{ label: 'Official Knossos hours and tickets', href: 'https://www.hh.gr/en/destinations/knossos/' }],
});

const spinalonga = mk({
  name: 'Spinalonga from Plaka + Elounda swim', carouselId: 'crete-spinalonga',
  images: photoCarousel('crete-spinalonga'), lat: 35.2978, lng: 25.7388,
  cost: 'Official admission is currently €20 full / €10 reduced. Plaka boats list about €12 adult / €6 child, so a realistic family visit is roughly €75–€105 before food. Buy the monument ticket through Hellenic Heritage and the boat locally from a licensed operator.',
  climate: '<b>Take an early Plaka boat.</b> The island is exposed, reflective and mostly unshaded. A 60–90 minute circuit before midday heat leaves the afternoon for a calm Mirabello swim.',
  save: 'Drive to Plaka and use the short 5–10 minute crossing instead of a full-day resort excursion.',
  splurge: 'A small boat that pairs the monument with a protected Kolokytha swim and real shade.',
  restos: ['<b>Giovanni’s, Plaka</b> — waterfront grilled dishes plus pasta and fries.', '<b>Ergospasio, Elounda</b> — polished harbor meal with plain sides.', '<b>Del Mar Snack Bar, Elounda</b> — burgers, pizza and crepes.'],
  alts: ['<b>Elounda beach + Plaka lunch</b> if wind cancels boats.', '<b>Agios Nikolaos lake walk</b> for a fully land-based day.'],
  blogs: [{ label: 'Official Spinalonga visitor information', href: 'https://www.hh.gr/en/destinations/spinalonga/' }, { label: 'Current Plaka boat fares', href: 'https://www.spinalongatours.gr/information' }],
});

const voulisma = mk({
  name: 'Voulisma Beach + Kritsa village', carouselId: 'crete-voulisma',
  images: photoCarousel('crete-voulisma'), lat: 35.1233, lng: 25.7441,
  cost: 'Beach access is free; budget parking, two loungers/umbrella if wanted, and lunch. Kritsa village wandering is free. Treat the short Kritsa Gorge as optional and never enter in heat, flood risk, or without proper shoes.',
  climate: '<b>Swim in the morning.</b> June water is typically around 73–74°F; wind can still change clarity and comfort. Move inland to Kritsa only after the strongest sun softens.',
  save: 'Pack shade, breakfast and plenty of water; use a village taverna rather than a beach-club package.',
  splurge: 'Two front-row loungers and a late lunch with a Mirabello view.',
  restos: ['<b>Pelagos, Kalo Chorio</b> — grilled food, pasta and fries.', '<b>Platanos, Kritsa</b> — village plates and straightforward grilled meats.', '<b>Agios Nikolaos Lidl / Sklavenitis</b> — breakfast and beach-picnic reset.'],
  alts: ['<b>Kitroplateia Beach</b> in Agios Nikolaos if the east-coast wind is better there.', '<b>Kritsa village only</b> for a slower culture-and-food day.'],
  blogs: [{ label: 'Voulisma destination guide', href: 'https://www.discovercrete.com/places-to-go/voulisma-beach-a-water-sports-paradise' }],
});

const agios = mk({
  name: 'Agios Nikolaos: Lake Voulismeni + Kitroplateia', carouselId: 'crete-agios-reset',
  images: photoCarousel('crete-agios-reset'), lat: 35.1908, lng: 25.7164,
  cost: 'The lake promenade, harbor and Kitroplateia Beach are free. Keep €40–€80 for a final waterfront meal and optional loungers.',
  climate: '<b>A low-output final day.</b> Use morning shade for the lake and town, swim when the wind/flags cooperate, and keep the afternoon for packing and an early dinner.',
  save: 'Walk from the apartment, use the town beach and make lunch the main meal.',
  splurge: 'A final early dinner overlooking Lake Voulismeni at golden hour.',
  restos: ['<b>Karnagio, Lake Voulismeni</b> — broad Cretan menu with grilled and pasta fallbacks.', '<b>O Nontas, Kitroplateia</b> — waterfront plates and kid-friendly sides.', '<b>La Strada</b> — pizza and pasta close to the lake.'],
  alts: ['<b>Repeat Voulisma</b> if everyone wants one more big beach.', '<b>Havania Beach</b> for a simple north-of-town swim.'],
  blogs: [{ label: 'Agios Nikolaos official destination guide', href: 'https://www.discovercrete.com/places-to-go/agios-nikolaos-an-international-cosmopolitan-resort' }],
});

const rethymnoReset = { ...structuredClone(rethymno), name: 'Rethymno beach reset + old-town food loop', carouselId: 'crete-rethymno-reset', images: photoCarousel('crete-rethymno-reset') };
const agiosReset = { ...structuredClone(agios), name: 'Mirabello flex day: Agios Nikolaos at family pace', carouselId: 'crete-agios-reset' };

const days = [
  H.travelDay('day0', '0', 'Wed &middot; Jun 9', 'Depart Pittsburgh for Chania', 'Overnight flight', '$$', [H.fact('Observed itinerary', 'American + British Airways via ORD and LHR; 18h49 to CHQ on the exact date.')], 'Keep all disruption-sensitive legs on one protected ticket.'),
  H.day('day1', 'c1', '1', 'Thu &middot; Jun 10', 'Arrive Chania and let the harbor do the work', 'Soft landing', '$$', [H.fact('Sleep', 'Chania night 1 of 5'), H.fact('Arrival', 'Observed CHQ arrival 5:45 p.m.')], 'Pick up the automatic, check in, eat and walk only as far as energy allows.', [chania]),
  H.day('day2', 'c1', '2', 'Fri &middot; Jun 11', 'Chania old town + easy town-beach swim', 'Town + water', '$$', [H.fact('Sleep', 'Chania night 2 of 5'), H.fact('Pace', 'Walkable day; no major drive')], 'A proper reset before the three west-Crete day trips.', [chania]),
  H.day('day3', 'c1', '3', 'Sat &middot; Jun 12', 'Balos and Gramvousa by Kissamos boat', 'Headline water day', '$$$', [H.fact('Sleep', 'Chania night 3 of 5'), H.fact('Family fare', 'About €147 before meals at current published rates')], 'The boat avoids the rough peninsula road; wind and operator status decide the day.', [balos]),
  H.day('day4', 'c1', '4', 'Sun &middot; Jun 13', 'Elafonissi early, Falasarna only if energy stays high', 'Lagoon + sunset option', '$$', [H.fact('Sleep', 'Chania night 4 of 5'), H.fact('Rule', 'One great beach is enough')], 'Start at Elafonissi before tour buses; Falasarna is an optional west-coast finish, not a command.', [elafonissi]),
  H.day('day5', 'c1', '5', 'Mon &middot; Jun 14', 'Imbros Gorge + south-coast swim', 'Family hike', '$$', [H.fact('Sleep', 'Chania night 5 of 5'), H.fact('Trail', 'Shorter and more family-scaled than full Samaria')], 'Use a taxi/shuttle plan for the one-way gorge and skip it entirely in extreme heat.', [imbros]),
  H.day('day6', 'c2', '6', 'Tue &middot; Jun 15', 'Move to Rethymno through the old town', 'Short transfer + town', '$$', [H.fact('Sleep', 'Rethymno night 1 of 3'), H.fact('Drive', 'About 1h15 before stops')], 'The first of only two lodging moves; park once and walk the Venetian core.', [rethymno]),
  H.day('day7', 'c2', '7', 'Wed &middot; Jun 16', 'Preveli Palm Beach + controlled Kourtaliotiko access', 'Gorge + water', '$$', [H.fact('Sleep', 'Rethymno night 2 of 3'), H.fact('Access', 'Kourtaliotiko now uses mandatory controlled entry')], 'Book the official gorge slot when 2027 inventory opens; do not improvise roadside access.', [preveli]),
  H.day('day8', 'c2', '8', 'Thu &middot; Jun 17', 'Rethymno beach reset and food-focused evening', 'Recovery day', '$$', [H.fact('Sleep', 'Rethymno night 3 of 3'), H.fact('Flex', 'Move here whichever west-Crete day needs weather help')], 'Laundry, beach, Fortezza and gelato—deliberately no major drive.', [rethymnoReset]),
  H.day('day9', 'c3', '9', 'Fri &middot; Jun 18', 'Knossos at opening, then move to Agios Nikolaos', 'Culture + transfer', '$$$', [H.fact('Sleep', 'Agios Nikolaos night 1 of 4'), H.fact('Holiday', 'Juneteenth observed; no PTO used')], 'Use the long island crossing to earn a genuinely different eastern-Crete chapter.', [knossos]),
  H.day('day10', 'c3', '10', 'Sat &middot; Jun 19', 'Spinalonga from Plaka + Elounda swim', 'History + boat + water', '$$$', [H.fact('Sleep', 'Agios Nikolaos night 2 of 4'), H.fact('Crossing', 'Plaka boat about 5–10 minutes')], 'Early monument circuit, shaded lunch, then swim—never the reverse in June heat.', [spinalonga]),
  H.day('day11', 'c3', '11', 'Sun &middot; Jun 20', 'Voulisma Beach + Kritsa village', 'Turquoise water + village', '$$', [H.fact('Sleep', 'Agios Nikolaos night 3 of 4'), H.fact('Drive', 'Roughly 15–25 minutes per leg from town')], 'The easiest high-quality swim of the eastern block, with a low-key inland finish.', [voulisma]),
  H.day('day12', 'c3', '12', 'Mon &middot; Jun 21', 'Mirabello flex day + final Agios Nikolaos evening', 'Swim + pack', '$$', [H.fact('Sleep', 'Agios Nikolaos night 4 of 4'), H.fact('Purpose', 'Weather retry or pure recovery')], 'Protect the return by ending close to HER and packing before dinner.', [agiosReset]),
  H.travelDay('day13', '13', 'Tue &middot; Jun 22', 'Heraklion to Pittsburgh on the practical same-day return', 'Return flight', '$$', [H.fact('Observed option', 'HER 8:40 a.m. via ATH and ORD; PIT 7:28 p.m.; 17h48 total.'), H.fact('Protection', 'Reconfirm final ticketing, baggage and connection protection before purchase')], 'This gets home the same day and preserves every Pittsburgh commitment day.'),
];

const mapColors = { chania: '#1f6f78', rethymno: '#c25a3a', east: '#3f7d4e', transfer: '#7d5ba6' };
const mapPoints = [
  H.point('Chania Airport (CHQ)', 35.5317, 24.1497, 'transfer', 'flight'), H.point('Chania base', 35.517, 24.017, 'chania', 'hotel'),
  H.point('Balos Lagoon', 35.5836, 23.5906, 'chania', 'beach'), H.point('Elafonissi', 35.2716, 23.5407, 'chania', 'beach'),
  H.point('Imbros Gorge', 35.2508, 24.1672, 'chania', 'hike'), H.point('Rethymno base', 35.3694, 24.473, 'rethymno', 'hotel'),
  H.point('Preveli Palm Beach', 35.1531, 24.4722, 'rethymno', 'beach'), H.point('Kourtaliotiko Gorge', 35.2038, 24.4646, 'rethymno', 'hike'),
  H.point('Knossos Palace', 35.2989, 25.1631, 'transfer', 'view'), H.point('Agios Nikolaos base', 35.1908, 25.7164, 'east', 'hotel'),
  H.point('Spinalonga', 35.2978, 25.7388, 'east', 'view'), H.point('Voulisma Beach', 35.1233, 25.7441, 'east', 'beach'),
  H.point('Kritsa village', 35.1581, 25.6442, 'east', 'town'), H.point('Heraklion Airport (HER)', 35.3397, 25.1803, 'transfer', 'flight'),
];

const { headBody, navToMain } = H.sliceChrome(template.parts[0].html, 'Crete: Chania · Rethymno · Agios Nikolaos — June 2027');
const creteNav = navToMain
  .replace('      <a href="#kids-favorites">Kids&rsquo; Favorites</a>\n', '')
  .replace(
    '      <a href="#packing">Packing</a><a href="#social">What People Say</a>\n',
    '      <a href="#packing">Packing</a><a href="#photo-guide">Photo Guide</a><a href="#food-guide">Food Guide</a><a href="#social">Field Notes</a>\n',
  );
const hero = H.preview({ kicker: 'Pittsburgh family of 4 · Jun 9–22, 2027', h1Main: 'Crete', h1Sub: 'West Lagoons to Mirabello Bay', lead: 'A true standalone island itinerary: five Chania nights for lagoons and a family gorge, three Rethymno nights for the palm coast, then four Agios Nikolaos nights for Knossos, Spinalonga and the clearest eastern swims.', stats: [['12', 'hotel nights'], ['3', 'bases'], ['$11.2k–15.0k', 'planning band'], ['8', 'PTO days']], split: [[45, 'Water + coast', 's1'], [30, 'Towns + food', 's2'], [25, 'Nature + hikes', 's3']], images: [
  [asset('google_balos_gramvousa_view_02.jpg'), 'Day 3 · West Crete', 'Balos Lagoon', 'The white-sand lagoon and Gramvousa boat day that anchors the western block.'],
  [asset('google_preveli_river_sea_01.jpg'), 'Day 7 · South Crete', 'Preveli Palm Beach', 'A palm river, Libyan Sea swim and controlled gorge access from Rethymno.'],
  [asset('google_spinalonga_golden_hour_02.jpg'), 'Day 10 · East Crete', 'Spinalonga', 'A short Plaka crossing to the fortified island, followed by calm Mirabello water.'],
  [asset('google_agios_harbor_twilight_01.jpg'), 'Day 12 · East Crete', 'Lake Voulismeni', 'A deliberately easy final chapter of town, beach, food and golden-hour light.'],
] });
const overview = `<section id="overview">${H.sectionLabel('The Plan at a Glance', 'Crete is big enough for the whole trip', 'This version stops treating Crete as a second-half add-on and gives west, central and east Crete enough time to feel distinct.')}<div class="overview"><div class="ocard"><p class="eyebrow">5 nights</p><h4>Chania</h4><p>Harbor, Balos, Elafonissi and Imbros—with one soft arrival and no Samaria endurance test.</p></div><div class="ocard"><p class="eyebrow">3 nights</p><h4>Rethymno</h4><p>Walkable Venetian evenings, Preveli/Kourtaliotiko and one genuine reset day.</p></div><div class="ocard"><p class="eyebrow">4 nights</p><h4>Agios Nikolaos</h4><p>Knossos en route, Spinalonga, Voulisma, Kritsa and a calm Mirabello finish near HER.</p></div></div><div class="tldr"><b>Recommendation:</b> a 39/55 standalone option. It matches the best hybrids on raw experience score, avoids an internal flight, and lands at the preferred $15k ceiling—but still needs a protected final flight checkout.</div></section>`;
const why = `<section id="why-this-trip" class="divider">${H.sectionLabel('Why Standalone Crete', 'Less transit, more island')}<div class="plan-grid">${H.card('One island, three personalities', '<p>Chania delivers the postcard west, Rethymno adds the south-coast palm/gorge day, and Mirabello Bay makes eastern Crete more than an airport exit.</p>')}${H.card('Family-scaled hiking', '<p>Imbros replaces the full Samaria commitment. The trip still has real limestone drama, but the eight-year-old gets a shorter one-way gorge and a coast reward.</p>')}${H.card('No sacrificial transition day', '<p>There is no Portugal/Madeira-to-Greece flight. The two base moves are driveable sightseeing days, and the long eastbound move earns Knossos.</p>')}</div></section>`;
const stays = `<section id="stays" class="divider">${H.sectionLabel('Where to Stay', 'Three apartment-first bases', 'Require AC, parking, laundry, kitchen and two real sleeping zones; keep every rate refundable until the flight ticket is protected.')}<div class="plan-grid">${H.card('Chania · 5 nights', H.prow('Zone', 'Nea Chora / old-town edge') + H.prow('Band', '$875–$1,400') + '<p class="tip">Walk to dinner and a town beach; drive outward early.</p>')}${H.card('Rethymno · 3 nights', H.prow('Zone', 'Old-town edge / beach east') + H.prow('Band', '$525–$850') + '<p class="tip">Parking matters more than a postcard lane address.</p>')}${H.card('Agios Nikolaos · 4 nights', H.prow('Zone', 'Lake / Kitroplateia walking radius') + H.prow('Band', '$700–$1,150') + '<p class="tip">Keep the final block within about an hour of HER.</p>')}</div></section>`;
const calendar = H.calendarGrid({ window: [2027, 6, 9, 6, 22], intro: 'The exact flight times are observed September 10, 2026 snapshots; activity blocks show sequence rather than promised operating hours.', tripDays: days.map((_, i) => ({ date: [6, 9 + i], blocks: i === 0 || i === 13 ? [{ act: 'air', start: i ? 7 : 18, end: i ? 20 : 22, label: i ? 'HER → PIT' : 'PIT → CHQ' }] : [{ act: i === 6 || i === 9 ? 'car' : [3, 4, 7, 10, 11, 12].includes(i) ? 'water' : i === 5 ? 'hike' : 'town', start: 8, end: 18, label: days[i].heading.replace(/&[^;]+;/g, ' ').slice(0, 25) }] })) });

const mapAirGround = `<section id="map" class="divider">${H.sectionLabel('The Whole Trip, Mapped', 'West to east without backtracking')}<div class="tripmap-wrap"><div class="mapbtns"><button data-region="chania"><span class="sw" style="background:#1f6f78"></span>Chania</button><button data-region="rethymno"><span class="sw" style="background:#c25a3a"></span>Rethymno</button><button data-region="east"><span class="sw" style="background:#3f7d4e"></span>East Crete</button><button data-region="all">Whole trip</button></div><div class="mapstage"><button class="layers-btn" aria-expanded="false" aria-label="Map layers"><span class="lbi">▧</span> Layers</button><div class="layers-panel" hidden><div class="layers-top"><strong>Map layers</strong><button class="layers-x" aria-label="Close">×</button></div><div class="layers-acts"><button data-all="1">Select all</button><span class="dot">·</span><button data-all="0">Deselect all</button></div><div class="layers-list"></div></div><div id="tripmap"></div></div></div></section><section id="air-travel" class="divider">${H.sectionLabel('Air Travel', 'CHQ in, HER out', 'Exact-date Google Flights snapshot reviewed Sep 10, 2026; prices can move until ticketed.')}<div class="plan-grid">${H.card('Practical observed itinerary', H.prow('Outbound', 'PIT–ORD–LHR–CHQ · Jun 9/10 · 18h49') + H.prow('Return', 'HER–ATH–ORD–PIT · Jun 22 · 17h48') + H.prow('Fare', '$1,304 per adult · $5,216 base family fare') + '<p class="tip">Plan $5,600–$6,500 after seats and bags. Re-run the exact multi-city search and confirm every connection is protected on the issued ticket.</p>')}${H.card('What was rejected', H.prow('Cheapest', '$1,265 per adult') + H.prow('Problem', '21-hour LHR return layover; PIT arrival Jun 23') + H.prow('One-stop outbound', '$1,510 per adult') + '<p class="tip">The $1,304 return is worth the small premium because it gets the family home the same day.</p>')}</div></section><section id="getting-around" class="divider">${H.sectionLabel('Getting Around', 'One automatic car, two deliberate moves')}<div class="plan-grid">${H.card('Rental-car baseline', H.prow('Pickup / return', 'CHQ / HER open-jaw') + H.prow('Planning band', '$850–$1,250 incl. fuel/parking') + H.prow('Must have', 'Automatic + full coverage + second driver') + '<p class="tip">An open-jaw drop fee is acceptable if it prevents a 2.5-hour backtrack to Chania.</p>')}${H.card('Drive rules', H.prow('Chania → Rethymno', 'about 1h15') + H.prow('Rethymno → Knossos → Agios', 'full sightseeing day') + H.prow('Balos', 'use Kissamos boat') + '<p class="tip">Never let Google’s optimistic mountain-road ETA turn a beach or gorge day into a race.</p>')}</div></section>`;
const healthTiming = `<section id="health-check" class="divider">${H.sectionLabel('Plan Health-Check', 'Strong route, live gates remain')}<div class="hc-grid"><div class="hc good"><span class="hc-tag">Route</span><h4>No internal flight</h4><p>Three bases create variety without airports, ferries or one-night hotels.</p></div><div class="hc good"><span class="hc-tag">Family fit</span><h4>Imbros, not full Samaria</h4><p>The headline gorge is shorter, and every exposed day has a beach/town alternative.</p></div><div class="hc watch"><span class="hc-tag">Flight gate</span><h4>Fare seen; protection unverified</h4><p>Exact dates and same-day return are real search results, but final through-ticket and baggage rules still require checkout review.</p></div><div class="hc watch"><span class="hc-tag">Heat/fire</span><h4>Early starts are operating policy</h4><p>June is generally comfortable, but gorge, archaeology and island-monument days need heat, wind and fire checks.</p></div></div></section><section id="timing" class="divider">${H.sectionLabel('Best Window', 'Jun 9–22 is the efficient line')}<div class="timing-compare"><div class="tcard best"><span class="tlabel">Canonical</span><h4>Wed Jun 9 – Tue Jun 22</h4><p>Twelve hotel nights, eight PTO days and a same-day scheduled return.</p></div><div class="tcard"><span class="tlabel">Why it works</span><h4>Juneteenth observed Fri Jun 18</h4><p>The federal holiday removes one PTO day during the eastbound move.</p></div><div class="tcard"><span class="tlabel">Hard rule</span><h4>Pittsburgh Jun 24–26</h4><p>The plan keeps Jun 23 as a disruption buffer and protects all required full days.</p></div></div><div class="verdict-box"><b>PTO math:</b> Jun 9–11 (3) + Jun 14–17 (4) + Jun 21–22 (2) − Juneteenth observed Jun 18 = <b>8 PTO days</b>.</div></section>`;
const budgetTips = `<section id="budget" class="divider">${H.sectionLabel('Budget', '$11,200–$15,000 for four', 'The high case lands exactly at the preferred ceiling; this remains a medium-confidence planning band.')} ${H.table(['Line item', 'Family of 4'], [['Flights, seats and bags', '$5,600–$6,500'], ['Lodging · 12 nights', '$2,100–$3,400'], ['Automatic car, fuel, parking', '$1,100–$1,600'], ['Food and groceries', '$1,700–$2,300'], ['Activities and boats', '$700–$1,200']])}<div class="twocol"><div class="listcard save-list"><h4>How the low case works</h4><ul><li>Apartment breakfasts and beach/gorge picnics.</li><li>Standard Balos boat and short Plaka crossing.</li><li>One car for the whole trip, with no internal airfare.</li></ul></div><div class="listcard splurge-list"><h4>Protect these</h4><ul><li>Automatic with proper coverage.</li><li>Good Chania and Agios Nikolaos locations.</li><li>A licensed guide at Knossos if the kids want the story.</li></ul></div></div></section><section id="totals" class="divider">${H.sectionLabel('Bottom Line', 'A $15k-ceiling contender')} ${H.table(['Category', 'Estimate'], [['Transportation', '$6,700–$8,100'], ['Lodging', '$2,100–$3,400'], ['Food', '$1,700–$2,300'], ['Activities', '$700–$1,200'], ['Grand total', '$11,200–$15,000']], 'budget-tbl grand')}<p class="rate-note">The category high cases are not mechanically simultaneous; the reconciled total band caps the realistic combined high case at $15,000. Requote all 2027 components before purchase.</p></section><section id="tips" class="divider">${H.sectionLabel('Booking Order', 'Protect the route before the beach days')}<div class="tips-order"><ol><li>Re-run and protect PIT→CHQ / HER→PIT<span> · first</span></li><li>Hold three refundable apartments<span> · after flight shape passes</span></li><li>Reserve CHQ→HER automatic car<span> · with full terms</span></li><li>Book Balos and Spinalonga boats<span> · weather cancellation visible</span></li><li>Buy Knossos and Kourtaliotiko slots<span> · when 2027 inventory opens</span></li><li>Recheck fire, heat, gorge and wind status<span> · week/day of</span></li></ol></div><div class="tips-grid">${H.tipcard('Flight rule', 'A fare screenshot is not a protected ticket', [{ flag: '<b>Do not buy</b> until baggage through-check and misconnect protection are explicit.' }, 'Keep the same-day HER return unless its connection rules fail.'])}${H.tipcard('Heat rule', 'Move exposed sites to opening time', ['Knossos and Spinalonga first thing.', 'Swim or shaded town time after lunch.', 'Treat gorge closures and extreme heat as automatic reroutes.'])}</div></section>`;
const socialBalanceStatus = `<section id="social" class="divider">${H.sectionLabel('Field Notes', 'The small rules that keep Crete fun')}<div class="tips-grid">${H.tipcard('West Crete', 'Choose one payoff per day', ['Balos by boat, not the rough access road.', 'Elafonissi first; Falasarna only if the family still wants it.', 'Imbros is the planned gorge; Samaria is intentionally absent.'])}${H.tipcard('Central Crete', 'Rethymno is the decompression valve', ['Keep one beach/laundry day movable.', 'Kourtaliotiko is controlled access—use the official system.', 'Park once and walk the old town.'])}${H.tipcard('East Crete', 'The chapter, not the airport night', ['Knossos turns the transfer into a culture day.', 'Plaka shortens the Spinalonga crossing.', 'Voulisma and Kitroplateia provide repeatable swim options.'])}</div></section><section id="balance" class="divider">${H.sectionLabel('Trip Balance', 'Water leads without flattening the island')}<div class="bar"><i style="width:45%;background:#1f6f78"></i><i style="width:30%;background:#c25a3a"></i><i style="width:25%;background:#3f7d4e"></i></div><div class="balance"><div class="bcard k1"><div class="pct">45%</div><h4>Water + coast</h4><p>Balos, Elafonissi, Preveli, Elounda, Voulisma and town beaches.</p></div><div class="bcard k2"><div class="pct">30%</div><h4>Towns + food</h4><p>Chania, Rethymno, Kritsa, Plaka and Agios Nikolaos.</p></div><div class="bcard k3"><div class="pct">25%</div><h4>Nature + history</h4><p>Imbros, Kourtaliotiko, Knossos and Spinalonga.</p></div></div></section><section id="status" class="divider">${H.sectionLabel('Decisions', 'Settled & still open')}<div class="status"><div class="scol settled"><h4>Settled</h4><div class="row"><b>Dates</b><span>Jun 9–22; 12 hotel nights; 8 PTO days.</span></div><div class="row"><b>Bases</b><span>Chania 5 + Rethymno 3 + Agios Nikolaos 4.</span></div><div class="row"><b>Airports</b><span>CHQ inbound / HER outbound.</span></div><div class="row"><b>Score</b><span>39/55 after shared-rubric rescore.</span></div></div><div class="scol open"><h4>Still Open</h4><div class="row"><b>Ticket</b><span>Final through-ticket, baggage and connection protection.</span></div><div class="row"><b>Lodging</b><span>Exact refundable apartments and all-in taxes.</span></div><div class="row"><b>2027 access</b><span>Knossos slots, Kourtaliotiko controls and boat schedules.</span></div><div class="row"><b>ETIAS</b><span>Verify rollout, fee and eligibility before travel.</span></div></div></div></section>`;

const scorecard = { displayName: 'Crete: Chania + Rethymno + Agios Nikolaos', blurb: 'One-island depth: lagoons, gorges, Venetian towns and Mirabello Bay', axes: { budget: 2, weather: 4, fireRisk: 3, swim: 4, variety: 5, ease: 3, food: 4, risk: 3, nights: 5, novelty: 4, pto: 3 }, weightDefaults: { budget: 2, weather: 1, fireRisk: 1, swim: 1, variety: 1, ease: 1, food: 1, risk: 1, nights: 1, novelty: 1, pto: 0 }, budget: { floorUsd: 11200, ceilUsd: 15000, targetUsd: 12000, preferredMaxUsd: 15000 }, pto: { days: 8, nights: 12 }, facets: { continent: 'europe', maxConnections: 2, swimTempF: [73, 74], noPassport: false, singleTicket: false, hasSwim: true }, totalBaked: 39 };

const preDepartureTodos = { labelHtml: '<p class="eyebrow">Pre-Departure To-Do</p><h2>Book in risk order</h2><p>Only the flight dates and observed fare options are current. Everything else stays refundable until the ticket is protected.</p>', blocks: [
  { when: 'Now–Nov 2026', tone: 'watch', title: 'Track the exact open jaw', items: ['Set PIT→CHQ / HER→PIT alerts for Jun 9/22.', 'Hold cancellable two-bedroom stays in all three bases.', 'Do not accept the 21-hour LHR return just to save $39 per adult.'] },
  { when: 'When ready to buy', tone: 'hot', title: 'Inspect the ticket', items: ['Confirm one issued itinerary or explicit interline protection.', 'Price assigned seats, checked bags and open-jaw car together.', 'Preserve the Jun 22 same-day Pittsburgh arrival.'] },
  { when: '90–30 days out', tone: 'watch', title: 'Lock controlled access', items: ['Book Knossos timed entry and the official Kourtaliotiko slot.', 'Choose Balos and Spinalonga operators with wind cancellation terms.', 'Recheck ETIAS and Greece driving-document requirements.'] },
  { when: 'Final week', tone: 'done', title: 'Let conditions move the days', items: ['Check heat, wind, fire and gorge closures daily.', 'Move the Rethymno and Agios flex days wherever the forecast needs them.', 'Download maps, tickets and the plain-food list.'] },
], callout: '<b>Current route status:</b> exact-date air inventory and a practical same-day return were observed. The route becomes booking-ready only after final checkout proves protection, baggage and connection terms.' };

const photoGuide = { html: `<section id="photo-guide" class="divider">${H.sectionLabel('Photography Guide', 'Crete rewards edge light and midday water', 'Use golden hour for harbors and villages; use higher sun when turquoise lagoons are the subject.')}<div class="tips-grid">${H.tipcard('Chania + Rethymno', 'Harbor light', ['Chania lighthouse from the east harbor wall at sunrise or sunset.', 'Rethymno Fortezza toward the old town in late light.', 'Carry one fast prime for blue-hour lanes, but travel light on beach days.'])}${H.tipcard('Lagoons + palm coast', 'Polarizer with restraint', ['Balos overlook wants 24–70mm context; the sandbar wants higher sun.', 'Elafonissi color is strongest before crowds and harsh glare.', 'Preveli works best from above before descending; protect gear from sand and salt.'])}${H.tipcard('East Crete', 'History plus aerial geometry', ['Knossos at opening for clean walkways and softer shadows.', 'Spinalonga compositions work from the Plaka boat and inside the ramparts.', 'Lake Voulismeni is the final golden-hour frame; Voulisma is the midday color frame.'])}</div><div class="verdict-box"><b>Kit:</b> 16–35mm, 24–70mm, optional 70–200mm, CPL, microfiber cloth, compact rain cover and a small day bag. Drones require current Greek aviation/archaeological-site permission—do not assume the aerial reference images are reproducible.</div></section>` };
const foodGuide = { html: `<section id="food-guide" class="divider">${H.sectionLabel('Food Guide', 'Cretan food with a plain-food escape hatch in every base', 'Apartment kitchens and full supermarkets keep picky-eater coverage real; restaurants remain recommendations to recheck before travel.')}<div class="plan-grid">${H.card('Chania', '<p><b>Adults:</b> bougatsa, dakos, grilled lamb, local cheese and harbor seafood.</p><p><b>Plain picks:</b> Laganon for fresh pasta; BaoTao for casual bowls; Nea Chora grills for chicken, bread and fries.</p><p><b>Groceries:</b> Sklavenitis / SYN.KA before remote west-coast days.</p>')}${H.card('Rethymno', '<p><b>Adults:</b> To Pigadi courtyard cooking, Stella’s home-style plates and meze.</p><p><b>Plain picks:</b> Casa di Hari pizza/pasta; Nostos gyros and fries; Angeli or Meli gelato.</p><p><b>Groceries:</b> restock before Preveli.</p>')}${H.card('Agios Nikolaos', '<p><b>Adults:</b> Karnagio, Plaka tavernas and Mirabello grilled fish.</p><p><b>Plain picks:</b> La Strada pizza/pasta; Del Mar burgers/crepes; grilled chicken and fries at village tavernas.</p><p><b>Groceries:</b> Lidl / Sklavenitis for beach breakfasts and the flight morning.</p>')}</div></section>` };

const main = { recommended: true, slug: 'crete', lang: 'en', title: 'Crete: Chania · Rethymno · Agios Nikolaos — June 2027', countries: ['greece'], packingTags: ['beach', 'hiking', 'heat'], overrides: { packing: ['<li><b>Gorge kit:</b> grippy closed-toe shoes, 2L water per person, hats and a hard heat turn-around rule.</li>', '<li><b>Swim kit:</b> water shoes, rash guards, reef-safe sunscreen, dry bag and familiar flotation gear where allowed.</li>', '<li><b>Driving:</b> International Driving Permit, automatic confirmation, offline maps and no unpaved Balos road.</li>'] }, hasPhotoGuide: true, hasFoodGuide: true, mapPoints, mapColors, itinerary: { className: 'divider', labelHtml: H.sectionLabel('Day by Day', 'The full 12-night standalone Crete itinerary', 'Every stop includes price context, June conditions, food fallbacks, alternatives and a map.'), daysClass: 'days', days }, preDepartureTodos, scorecard, parts: [
  { t: 'raw', html: `${headBody}${hero}${creteNav}${overview}${why}${stays}${calendar}` }, { t: 'itinerary' }, { t: 'raw', html: mapAirGround }, { t: 'entry' }, { t: 'raw', html: healthTiming }, { t: 'todo' }, { t: 'raw', html: budgetTips }, { t: 'packing' }, { t: 'photoGuide' }, { t: 'foodGuide' }, { t: 'raw', html: socialBalanceStatus }, { t: 'raw', html: H.mapScripts(template.parts[14].html, mapPoints, mapColors) },
] };

const evidence = { schemaVersion: 1, slug: 'crete', reviewedAt: '2026-09-10', overallConfidence: 'medium', axes: {
  budget: { score: 2, rationale: 'The reconciled family band is $11,200–$15,000. The high case reaches the preferred ceiling, but lodging and final ticket protection remain medium-confidence.', confidence: 'medium', evidence: ['budget-band'] },
  weather: { score: 4, rationale: 'June is predominantly dry and warm; early starts manage exposed archaeology, gorge and fortress days.', confidence: 'high', evidence: ['climate-proxy'] },
  fireRisk: { score: 3, rationale: 'Greece is inside official fire season in June; wind, gorge access and road closure create moderate disruption exposure with three-base flexibility.', confidence: 'medium', evidence: ['wildfire-exposure'] },
  swim: { score: 4, rationale: 'The itinerary schedules repeated natural-water days in the 73–74°F planning range, with multiple wind-direction alternatives.', confidence: 'medium', evidence: ['swim-conditions'] },
  variety: { score: 5, rationale: 'Substantial water, town/food, gorge/nature and archaeology/history modes are all scheduled.', confidence: 'high', evidence: ['itinerary-structure'] },
  ease: { score: 3, rationale: 'One island and no internal flight help, but three bases, two lodging moves, a two-stop outbound and several full driving days keep logistics moderate.', confidence: 'medium', evidence: ['operational-load'] },
  food: { score: 4, rationale: 'All three bases and remote days have named plain-food, grocery and apartment-kitchen fallbacks.', confidence: 'medium', evidence: ['family-food-coverage'] },
  risk: { score: 3, rationale: 'Exact-date inventory exists, but final ticket protection and several 2027 activity access rules remain open.', confidence: 'high', evidence: ['route-readiness'] },
  nights: { score: 5, rationale: 'Twelve hotel nights derive 5/5 under the shared rubric.', confidence: 'high', evidence: ['trip-window'] },
  novelty: { score: 4, rationale: 'Crete is new, but the family has visited several Greek islands, so this is mostly new with a familiar destination type.', confidence: 'high', evidence: ['visited-overlap'] },
  pto: { score: 3, rationale: 'Eight PTO days derive 3/5 and have zero default weight.', confidence: 'high', evidence: ['trip-window'] },
}, facts: [
  { id: 'budget-band', category: 'budget', proxyStatus: 'current-proxy', confidence: 'medium', sourceRefs: ['google-flights-2027-current-audit', 'internal-itinerary'], value: { lowUsd: 11200, highUsd: 15000 }, verifiedAt: '2026-09-10', expiresAt: '2026-10-10', sourceLocators: { 'google-flights-2027-current-audit': 'Google Flights exact multi-city search PIT-CHQ Jun 9 and HER-PIT Jun 22, 2027; $1,304 practical adult fare', 'internal-itinerary': 'main.json budget and totals sections' }, claimType: 'mixed' },
  { id: 'trip-window', category: 'dates', proxyStatus: 'derived', confidence: 'high', sourceRefs: ['decision-profile'], value: { depart: '2027-06-09', return: '2027-06-22', hotelNights: 12, ptoDays: 8 }, verifiedAt: '2026-09-10', expiresAt: null, sourceLocators: { 'decision-profile': 'decisionProfile.json tripWindows.crete and Pittsburgh requiredFullDays' }, claimType: 'derived' },
  { id: 'climate-proxy', category: 'climate', proxyStatus: 'current-proxy', confidence: 'high', sourceRefs: ['meteo-heraklion-climate'], value: { temperatureF: [66, 81], rainfallMm: 3, score: 4 }, verifiedAt: '2026-09-10', expiresAt: '2027-04-01', sourceLocators: { 'meteo-heraklion-climate': 'Hellenic meteorological June climate normals for Heraklion used as Crete planning proxy' }, claimType: 'observed' },
  { id: 'wildfire-exposure', category: 'wildfire', proxyStatus: 'current-proxy', confidence: 'medium', sourceRefs: ['greece-fire-season-2026', 'effis-2024-fire-report'], value: { score: 3, chanceBand: '5–10%' }, verifiedAt: '2026-09-10', expiresAt: '2027-06-01', sourceLocators: { 'greece-fire-season-2026': 'Greek authority 2026 fire season dates May 1 through October 31', 'effis-2024-fire-report': 'EFFIS annual fire report supports recent Mediterranean June-through-September seasonality' }, claimType: 'derived' },
  { id: 'swim-conditions', category: 'swim', proxyStatus: 'current-proxy', confidence: 'medium', sourceRefs: ['noaa-oisst', 'internal-itinerary'], value: { score: 4, temperatureF: [73, 74], hasSwim: true, scheduledWaterDays: 6 }, verifiedAt: '2026-09-10', expiresAt: '2027-05-15', sourceLocators: { 'noaa-oisst': 'NOAA OISST June climatology proxy for waters surrounding Crete', 'internal-itinerary': 'main.json schedules Balos, Elafonissi, Preveli, Elounda, Voulisma and town beaches' }, claimType: 'mixed' },
  { id: 'itinerary-structure', category: 'itinerary', proxyStatus: 'derived', confidence: 'high', sourceRefs: ['internal-itinerary'], value: { score: 5, hotelNights: 12, bases: 3, waterPct: 45, townPct: 30, naturePct: 25 }, verifiedAt: '2026-09-10', expiresAt: null, sourceLocators: { 'internal-itinerary': 'crete/main.json day1-day12 and balance section' }, claimType: 'derived' },
  { id: 'operational-load', category: 'logistics', proxyStatus: 'current-proxy', confidence: 'medium', sourceRefs: ['internal-itinerary', 'google-flights-2027-current-audit'], value: { easeScore: 3, bases: 3, baseMoves: 2, internalFlights: 0, maxConnections: 2, singleTicket: false }, verifiedAt: '2026-09-10', expiresAt: '2026-10-10', sourceLocators: { 'internal-itinerary': 'crete/main.json air travel, getting around and daily route', 'google-flights-2027-current-audit': 'Exact-date UI search showed a two-stop outbound and two-stop practical return' }, claimType: 'mixed' },
  { id: 'family-food-coverage', category: 'food', proxyStatus: 'current-proxy', confidence: 'medium', sourceRefs: ['sklavenitis-crete-stores', 'internal-itinerary'], value: { score: 4, groceryCoverage: true, plainFoodRequired: true, plainFoodEveryBase: true }, verifiedAt: '2026-09-10', expiresAt: '2027-05-01', sourceLocators: { 'sklavenitis-crete-stores': 'Current operator store locator confirms full grocery coverage on Crete', 'internal-itinerary': 'crete/foodGuide.json and day-by-day restaurant fallbacks cover each base and remote day' }, claimType: 'mixed' },
  { id: 'route-readiness', category: 'route', proxyStatus: 'current-proxy', confidence: 'high', sourceRefs: ['google-flights-2027-current-audit'], value: { status: 'current-proxy', exactTripQuoteObserved: true, finalProtectionVerified: false, sameDayReturnObserved: true, singleTicket: false, maxConnections: 2 }, verifiedAt: '2026-09-10', expiresAt: '2026-10-10', sourceLocators: { 'google-flights-2027-current-audit': 'Exact multi-city PIT-CHQ Jun 9 and HER-PIT Jun 22 search reviewed live; $1,304 practical adult fare' }, claimType: 'observed' },
  { id: 'visited-overlap', category: 'novelty', proxyStatus: 'derived', confidence: 'high', sourceRefs: ['decision-profile'], value: { overlap: [], familiarType: 'Greek islands' }, verifiedAt: '2026-09-10', expiresAt: null, sourceLocators: { 'decision-profile': 'Visited list includes Santorini, Mykonos and Rhodes but not Crete' }, claimType: 'derived' },
], metrics: { airHours: 36.6, groundHours: 12, timeZones: 7, baseMoves: 2, longestTransferHours: 4.5, highOutputDayStreak: 3, fallbackDays: 2, childActivityFit: { age13: 'fits', age8: 'fits' }, lodgingComfort: { airConditioning: 'required', kitchen: 'required', laundry: 'required', realBeds: 'required' }, waterSafety: 'Daily wind, flag and operator checks; familiar flotation gear where allowed.', crowdingPressure: 'Early starts required for Knossos, Spinalonga, Balos and Elafonissi.', medicalAccess: 'Hospitals in Chania, Rethymno and Agios Nikolaos; remote gorge and lagoon days require conservative turn-around rules.' } };
const variants = { schemaVersion: 1, slug: 'crete', canonicalId: 'canonical', variants: [{ id: 'canonical', label: '12-night west-to-east Crete', canonical: true, status: 'documented', nights: 12, ptoDays: 8, budget: { lowUsd: 11200, expectedUsd: null, highUsd: 15000, distribution: 'planning-band', chanceUnderPreferredMax: null }, removedExperiences: [], notes: 'Chania 5 + Rethymno 3 + Agios Nikolaos 4, CHQ inbound and HER outbound.', confidence: 'medium', claimType: 'derived', sourceRefs: ['internal-itinerary'], sourceLocators: { 'internal-itinerary': 'crete/main.json canonical route' } }], alternateStatus: 'not-yet-evidence-backed', alternateNotes: 'A shorter or one-base version should be added only after its lost experiences and real savings are reconciled.' };

fs.mkdirSync(outDir, { recursive: true });
for (const [name, data] of [['main.json', main], ['photoGuide.json', photoGuide], ['foodGuide.json', foodGuide], ['evidence.json', evidence], ['variants.json', variants]]) {
  fs.writeFileSync(path.join(outDir, name), `${JSON.stringify(data, null, 2)}\n`);
}
console.log(`wrote ${path.relative(root, outDir)} itinerary bundle`);
